import { useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Icon } from '../app/icons';
import { CommunityPreview } from '../data/community';
import { useCommunityComponents } from '../hooks/useCommunityComponents';

export default function Community(){
  const navigate=useNavigate(); const {all,liked,loading,toggleLike,duplicateComponent,user}=useCommunityComponents(); const [filter,setFilter]=useState<'all'|'button'|'card'|'badge'|'custom'>('all'); const [copying,setCopying]=useState('');
  const remix=async(item:(typeof all)[number])=>{setCopying(item.id);try{const id=await duplicateComponent(item);navigate(`/components/mine/${id}`)}finally{setCopying('')}};
  const popular=useMemo(()=>[...all].filter(x=>x.visibility==='public').sort((a,b)=>b.likes-a.likes).slice(0,3),[all]); const visible=all.filter(x=>x.visibility==='public'&&(filter==='all'||x.type===filter));
  return <div className="page-stack community-page"><section className="page-heading"><div><span className="eyebrow">COMMUNITY GALLERY</span><h1>みんなのコンポーネント</h1><p>つくったUIを見つけて、いいねして、次のアイデアにつなげる。</p></div><Link to="/create" className="button primary"><Icon name="plus"/>コンポーネントを作る</Link></section>
    <section className="recommend-section"><div className="section-heading"><div><span className="eyebrow">RECOMMENDED</span><h2>いま人気のコンポーネント</h2></div><span className="recommend-note"><Icon name="sparkles"/>いいね数からピックアップ</span></div><div className="recommend-grid">{popular.map((item,i)=><article className="recommend-card" key={item.id}><span className="rank">0{i+1}</span><div className="community-preview"> <CommunityPreview item={item}/></div><div className="community-info"><div><h3>{item.name}</h3><p>by {item.authorName}</p></div><div className="community-actions"><button className="remix-button" disabled={copying===item.id} onClick={()=>void remix(item)} aria-label={`${item.name}を複製`}><Icon name="copy" size={14}/></button><button className={`like-button ${liked.includes(item.id)||item.likedBy?.includes(user?.uid||'local-user')?'liked':''}`} onClick={()=>void toggleLike(item)} aria-label={`${item.name}にいいね`}><Icon name="heart" size={15}/>{item.likes}</button></div></div></article>)}</div></section>
    <section><div className="section-heading"><div><h2>公開コンポーネント</h2><p>{loading?'読み込み中…':`${visible.length}件の作品`}</p></div><div className="filter-tabs">{(['all','button','card','badge','custom'] as const).map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x==='all'?'すべて':x}</button>)}</div></div><div className="community-grid">{visible.map(item=><article className="community-card" key={item.id}><div className="community-preview"><CommunityPreview item={item}/></div><div className="community-info"><div><h3>{item.name}</h3><p>{item.description}</p><small><span className="mini-avatar">{item.authorName[0]}</span>{item.authorName}</small></div><div className="community-actions"><button className="remix-button" disabled={copying===item.id} onClick={()=>void remix(item)} aria-label={`${item.name}を自分用に複製`} title="自分用に複製"><Icon name="copy" size={14}/></button><button className={`like-button ${liked.includes(item.id)||item.likedBy?.includes(user?.uid||'local-user')?'liked':''}`} onClick={()=>void toggleLike(item)} aria-label={`${item.name}にいいね`}><Icon name="heart" size={15}/>{item.likes}</button></div></div></article>)}</div></section>
  </div>
}
