import { Link } from 'react-router-dom';
import { Icon } from '../app/icons';
import { CommunityPreview, featuredComponents } from '../data/community';

export default function LandingPage(){
  return <div className="lp">
    <header className="lp-header"><Link to="/" className="lp-brand"><span><Icon name="layers" size={19}/></span>Componenter</Link><nav><a href="#features">できること</a><a href="#flow">使い方</a><Link to="/community">みんなの作品</Link></nav><Link to="/app" className="lp-header-cta">無料で始める <Icon name="arrow" size={15}/></Link></header>
    <main>
      <section className="lp-hero"><div className="lp-hero-copy"><span className="lp-kicker"><Icon name="sparkles" size={14}/> VISUAL COMPONENT WORKSPACE</span><h1>UIを、作る。<br/>集める。組み立てる。</h1><p>コードを書いても、画面を触ってもいい。コンポーネントを自由に作り、辞書に残し、次のページへ何度でも使えるワークスペース。</p><div className="lp-actions"><Link to="/app" className="lp-button primary">今すぐ作り始める <Icon name="arrow"/></Link><Link to="/community" className="lp-button">作品を見てみる</Link></div><small>アカウントなしでも、すぐに試せます。</small></div>
        <div className="lp-product-shot" aria-label="Componenterの編集画面イメージ"><div className="lp-shot-top"><i/><i/><i/><span>Component Studio</span></div><div className="lp-shot-body"><aside><small>STYLE</small><label>サイズ <span>240 px</span></label><b/><label>角丸 <span>18 px</span></label><b/><label>カラー</label><div className="lp-colors"><i/><i/><i/></div><label>HOVER</label><b/></aside><div className="lp-shot-canvas"><span>LIVE PREVIEW</span><button>Explore components <i>→</i></button><small>hoverして動きを確認</small></div><div className="lp-code-lines"><span>CSS</span><code>.button {'{'}</code><code> transition: .25s;</code><code> transform: scale(1);</code><code>{'}'}</code><code>.button:hover {'{'}</code><code> transform: scale(1.05);</code><code>{'}'}</code></div></div></div>
      </section>
      <section className="lp-trust"><span>直接触って調整</span><i/><span>HTML・CSS・JS対応</span><i/><span>公開・非公開を選択</span><i/><span>コードをそのまま持ち帰る</span></section>
      <section className="lp-section" id="features"><div className="lp-section-heading"><span className="lp-kicker">WHAT YOU CAN DO</span><h2>思いついた形を、<br/>使える部品にする。</h2><p>曖昧な指示ではなく、見た目と数値を自分の手で決める。作ったものは、その場限りにしません。</p></div><div className="lp-feature-grid"><article className="large"><span className="lp-feature-icon"><Icon name="wand"/></span><h3>細部まで視覚的に編集</h3><p>寸法、余白、色、境界線、影、文字、回転、アニメーションまで。スライダーと数値入力を使い分けられます。</p><div className="lp-control-demo"><label>角丸 <output>24 px</output></label><div><span/><i/></div><label>拡大率 <output>1.05 ×</output></label><div><span/><i/></div></div></article><article><span className="lp-feature-icon warm"><Icon name="code"/></span><h3>コードでも自由に作る</h3><p>HTML・CSS・JavaScriptを直接編集。クリック動作や疑似要素も、その場で実行して確かめられます。</p><pre><code>{`button::after {\n  content: "→";\n  transform: rotate(-8deg);\n}`}</code></pre></article><article><span className="lp-feature-icon green"><Icon name="book"/></span><h3>自分だけのUI辞書</h3><p>作ったコンポーネントを見た目で管理。公開範囲を選び、編集・複製しながら育てられます。</p><div className="lp-mini-library"><i/><i/><i/></div></article><article className="wide"><div><span className="lp-feature-icon pink"><Icon name="users"/></span><h3>作品から、次の工夫を見つける</h3><p>みんなが公開したUIを眺め、いいねして、自分用に複製。作者の工夫を起点に、新しい表現へつなげます。</p><Link to="/community" className="text-link">コミュニティを見る <Icon name="arrow"/></Link></div><div className="lp-social-demo"><span>01</span><div><b>Orbit Button</b><small>184 likes</small></div><Icon name="heart"/></div></article></div></section>
      <section className="lp-flow" id="flow"><div className="lp-section-heading"><span className="lp-kicker">SIMPLE FLOW</span><h2>作ったUIが、次の制作につながる。</h2></div><div className="lp-steps"><article><span>01</span><Icon name="plus"/><h3>作る</h3><p>ビジュアル操作またはコードで、コンポーネントを自由に制作。</p></article><article><span>02</span><Icon name="book"/><h3>残す</h3><p>名前や用途、公開範囲と一緒に自分の辞書へ保存。</p></article><article><span>03</span><Icon name="grid"/><h3>組み立てる</h3><p>保存した部品をページへ追加し、完成形をプレビュー。</p></article><article><span>04</span><Icon name="copy"/><h3>持ち帰る</h3><p>コードをコピーして、自分のプロジェクトでそのまま利用。</p></article></div></section>
      <section className="lp-showcase"><div className="lp-section-heading row"><div><span className="lp-kicker">MADE BY THE COMMUNITY</span><h2>みんなの工夫を見てみよう。</h2></div><Link to="/community" className="lp-button">すべての作品を見る <Icon name="arrow"/></Link></div><div className="lp-showcase-grid">{featuredComponents.slice(0,3).map(item=><article key={item.id}><div><CommunityPreview item={item}/></div><span>{item.type}</span><h3>{item.name}</h3><p>{item.description}</p><small>by {item.authorName}</small></article>)}</div></section>
      <section className="lp-final"><span className="lp-kicker">START CREATING</span><h2>最初のひとつを、<br/>今ここから。</h2><p>登録しなくても作成を始められます。気に入ったら、自分の辞書へ残してください。</p><Link to="/create" className="lp-button light">コンポーネントを作る <Icon name="arrow"/></Link></section>
    </main>
    <footer className="lp-footer"><Link to="/" className="lp-brand"><span><Icon name="layers" size={17}/></span>Componenter</Link><p>UIを、作る。集める。組み立てる。</p><div><Link to="/guide">使い方</Link><Link to="/community">みんなの作品</Link><Link to="/app">アプリを開く</Link></div><small>© 2026 Componenter</small></footer>
  </div>
}
