import { useState } from 'react';
import { Icon } from '../app/icons';
import { useAuth } from '../app/AuthContext';

const firebaseReady = Boolean(import.meta.env.VITE_FIREBASE_API_KEY && import.meta.env.VITE_FIREBASE_PROJECT_ID);
const githubReady = Boolean(import.meta.env.VITE_GITHUB_CLIENT_ID);

export default function Settings(){
  const { user, enabled, githubToken, login, logout } = useAuth(); const [repoName,setRepoName]=useState('componenter-ui'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const connect = async () => { setBusy(true); setMessage(''); try { await login(); setMessage('GitHubと接続しました。'); } catch(e) { setMessage(e instanceof Error?e.message:'接続に失敗しました。'); } finally { setBusy(false); } };
  const createRepo = async () => { if(!githubToken)return; setBusy(true);setMessage('');try{const response=await fetch('https://api.github.com/user/repos',{method:'POST',headers:{Authorization:`Bearer ${githubToken}`,'Content-Type':'application/json',Accept:'application/vnd.github+json'},body:JSON.stringify({name:repoName,private:true,description:'Created with Componenter'})});const result=await response.json() as {html_url?:string;message?:string};if(!response.ok)throw new Error(result.message||'リポジトリ作成に失敗しました。');setMessage(`作成しました: ${result.html_url}`)}catch(e){setMessage(e instanceof Error?e.message:'作成に失敗しました。')}finally{setBusy(false)}};
  return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">WORKSPACE SETTINGS</span><h1>設定・連携</h1><p>データ保存とコード管理の準備をします。</p></div>{user?<button className="button" onClick={()=>void logout()}>ログアウト</button>:<button className="button primary" disabled={!enabled||busy} onClick={()=>void connect()}><Icon name="github"/>GitHubでログイン</button>}</section>{message&&<div className="notice">{message}</div>}<section className="settings-section"><h2>サービス連携</h2><div className="integration-list"><article><span className="integration-icon firebase">◆</span><div><h3>Firebase</h3><p>GitHubログインとFirestoreによるビルダー内容のクラウド同期。</p><div className="env-list"><code>VITE_FIREBASE_API_KEY</code><code>VITE_FIREBASE_PROJECT_ID</code><code>VITE_FIREBASE_AUTH_DOMAIN</code></div></div><span className={`connection-badge ${firebaseReady?'ready':''}`}><i/>{firebaseReady?'設定済み':'未接続'}</span></article><article><span className="integration-icon github"><Icon name="github" size={25}/></span><div><h3>GitHub</h3><p>{user?`${user.displayName||user.email} として接続中。非公開リポジトリを作成できます。`:'生成コードの保存、リポジトリ作成、コンポーネントの取り込み。'}</p>{user&&githubToken?<div className="repo-form"><input value={repoName} onChange={e=>setRepoName(e.target.value)} aria-label="リポジトリ名"/><button className="button small" disabled={busy||!repoName.trim()} onClick={()=>void createRepo()}><Icon name="plus"/>非公開リポジトリを作成</button></div>:<div className="env-list"><code>VITE_GITHUB_CLIENT_ID</code><code>GitHub OAuth (Firebase Auth)</code></div>}</div><span className={`connection-badge ${user?'ready':''}`}><i/>{user?'接続済み':githubReady?'設定済み':'未接続'}</span></article><article><span className="integration-icon cloud"><Icon name="cloud" size={25}/></span><div><h3>Cloudflare Pages</h3><p>このViteアプリは <code>npm run build</code> の <code>dist</code> をそのまま公開できます。</p></div><span className="connection-badge neutral"><i/>デプロイ待ち</span></article></div></section><section className="setup-panel"><Icon name="book"/><div><h3>セットアップ手順</h3><ol><li><span>1</span><p>Firebase ConsoleでWebアプリを作成し、AuthenticationのGitHubプロバイダとFirestoreを有効化。</p></li><li><span>2</span><p><code>.env.example</code> を <code>.env.local</code> にコピーして各値を設定。</p></li><li><span>3</span><p>Cloudflare PagesでBuild commandを <code>npm run build</code>、Outputを <code>dist</code> に設定。</p></li></ol></div></section></div>}
